# Generated by Django 3.0.3 on 2020-08-28 03:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import vizApps.domain.StatusEnum
import vizApps.domain.TypeBoardEnum
import vizApps.domain.TypeVizEnum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISH', 'Publié')], default=vizApps.domain.StatusEnum.StatusEnum['DRAFT'], max_length=15)),
                ('type', models.CharField(choices=[('DASHBOARD', 'Dashboard'), ('RAPPORT', 'Rapport')], default=vizApps.domain.TypeBoardEnum.TypeBoardEnum['DASHBOARD'], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DataCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VizEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('type', models.CharField(choices=[('CHOROPLETH_MAP', 'Carte choropleth'), ('TABLE', 'Table'), ('BAR_GRAPH', 'Graphique en barre'), ('LINE_GRAPH', 'Graphique en ligne'), ('POINT_GRAPH', 'Graphique de point'), ('PARAM', 'Ensemble de paramettre')], default=vizApps.domain.TypeVizEnum.TypeVizEnum['TABLE'], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TraceEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dataConnectorParam', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vizApps.BoardEntity')),
                ('vizListe', models.ManyToManyField(to='vizApps.VizEntity', verbose_name='liste des viz')),
            ],
        ),
        migrations.AddField(
            model_name='boardentity',
            name='vizEntities',
            field=models.ManyToManyField(to='vizApps.VizEntity', verbose_name='liste des viz'),
        ),
    ]
