# Generated by Django 3.0.3 on 2020-08-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizApps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardentity',
            name='vizEntities',
            field=models.ManyToManyField(blank=True, to='vizApps.VizEntity', verbose_name='liste des viz'),
        ),
    ]
