# Generated by Django 3.0.3 on 2020-08-28 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vizApps', '0002_auto_20200828_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardentity',
            name='vizEntities',
        ),
    ]
