# Generated by Django 3.0.3 on 2020-08-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizApps', '0003_remove_boardentity_vizentities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceentity',
            name='vizListe',
            field=models.ManyToManyField(blank=True, to='vizApps.VizEntity', verbose_name='liste des viz'),
        ),
    ]
